version: "3"

volumes:
  mongodb_volume:

services:
  web_api:
    image: bohdanh01/express-mongodb-web-api
    container_name: web_api
    restart: always
    depends_on:
      - mongo
    ports:
      - 3000:3000
    environment:
      - TZ=Europe/Kiev
      - MONGO_DB_ADDR=mongo
      - MONGO_DB_PORT=27017
      - RUN_INTO_CONTAINER=true

  mongo:
    image: mvertes/alpine-mongo
    container_name: mongo
    restart: always
    volumes:
      - mongodb_volume:/data/db
    ports:
      - 27017:27017

  nginx:
    image: nginx:1.17.10-alpine
    container_name: nginx
    restart: always
    depends_on:
      - web_api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
